export type Lang = "de" | "en" | "es" | "fr";

const de = {
  gateTitle: "Plane deine Woche mit deinem Zyklus.",
  gateBody: "Termine, Sport und Pausen, passend zu deiner Phase.",
  signIn: "Anmelden",
  signUp: "Konto anlegen",
  guest: "Weiter ohne Konto",
  guestNote: "Gast-Modus, lokal auf diesem Gerät gespeichert.",
  loading: "Ich hol deinen Kalender.",
  authFail: "Die Anmeldung ist da, der Kalender erkennt sie noch nicht.",
  retry: "Noch einmal",
  revise: "Ausrichtung",
  signOut: "Abmelden",
  settings: "Einstellungen",
  food: "Was dir guttut",
  move: "Bewegung",
  month: "Monat",
  week: "Woche",
  year: "Jahr",
  dayView: "Tag",
  todayJump: "Heute",
  search: "Suchen",
  searchEmpty: "Nichts mit diesem Wort.",
  allDay: "Ganztägig",
  place: "Ort",
  remind: "Erinnerung",
  noRemind: "Keine",
  todayWord: "heute",
  checkin: "Wie geht's dir heute?",
  seeToday: "Heute ansehen",
  save: "Eingetragen",
  saving: "Ich leg's ab",
  back: "Zurück",
  note: "Notiz an mich…",
  bleed: "Blutung",
  bleedMaybe: "Blutung, falls sie da ist",
  energy: "Energie",
  low: "sehr schlecht",
  high: "sehr gut",
  symptoms: "Beschwerden",
  ovulation: "Eisprung heute",
  pain: "Schmerz",
  sleep: "Schlaf",
  heat: "Hitze",
  mood: "Stimmung",
  day: "Dieser Tag",
  appointment: "Termin",
  meal: "Mahlzeit",
  sport: "Sport",
  birthday: "Geburtstag",
  task: "Aufgabe",
  add: "Hinzufügen",
  title: "Was soll rein?",
  repeat: "Wiederholen",
  until: "Bis",
  onlyThis: "Nur diesen",
  wholeSeries: "Die ganze Reihe",
  moveDay: "Anderer Tag",
  once: "Einmal",
  daily: "Täglich",
  weekdays: "Mo–Fr",
  weekdaysSat: "Mo–Sa",
  weekly: "Wöchentlich",
  monthly: "Monatlich",
  quarterly: "Vierteljährlich",
  halfyearly: "Halbjährlich",
  yearly: "Jährlich",
  voice: "Sprich mit mir",
  voiceHint: "Tippe auf das Mikrofon und sprich – oder schreibe direkt hier rein.",
  listening: "Ich höre dich…",
  voiceLocal: "Ich habe das lokal verstanden. Ein Sprachdienst ist noch nicht verbunden.",
  share: "Kalender teilen",
  shareEmpty: "Noch keine Freigaben.",
  shareCopy: "Link kopieren",
  shareHide: "Phasen nicht mitgeben",
  shareAccept: "Annehmen",
  shareDone: "Kalender hinzugefügt – du siehst die Termine jetzt in deinem Kalender.",
  shareMissing: "Diese Einladung gibt es nicht mehr.",
  shareNeeds: "Dafür braucht es ein Konto.",
  shareSign: "Melde dich an, dann kannst du annehmen.",
  copied: "Link kopiert.",
  feed: "Kalender-Abo",
  feedCopy: "iCal-Link kopieren",
  feedHint: "Den Link kannst du in Apple oder Google Kalender als Abo einfügen.",
  push: "Benachrichtigungen",
  pushOn: "Erinnerungen einschalten",
  pushGap: "Push ist noch nicht verbunden. Ich merke mir, dass du erinnert werden willst – der Versand fehlt, bis die Schlüssel da sind.",
  pushOff: "Erinnerungen aus",
  pushReady: "Ich erinnere dich, wenn du es erlaubst. Sanft, nicht als Mahnung.",
  deleteAsk: "Profil wirklich löschen?",
  deleteBody: "Diese Aktion kann nicht rückgängig gemacht werden. Alle Logs, Aufgaben und Termine gehen mit.",
  deleteYes: "Ja, alles löschen",
  deleteNo: "Abbrechen",
  feedback: "Wie gefällt dir Fravia?",
  feedbackHint: "Was gefällt dir – und was kann ich besser machen?",
  feedbackThanks: "Danke für dein Feedback!",
  feedbackSend: "Abschicken",
  language: "Sprache",
  privacy: "Datenschutz",
  imprint: "Impressum",
  help: "Wenn etwas klemmt, schreib es mir hier. Ich ersetze keine Ärztin und keinen Notdienst.",
  install: "Fravia als App installieren",
  installIos: "In Safari teilen, dann „Zum Home-Bildschirm“.",
  update: "Neue Version verfügbar",
  reload: "Neu laden",
  take: "Diesen Kalender mitnehmen?",
  takeBody: "Was du ohne Konto eingetragen hast, liegt noch auf diesem Gerät.",
  takeYes: "Mitnehmen",
  leave: "Hier lassen",
  guestClear: "Lokale Daten löschen",
  importIcs: "Kalendertermine als .ics importieren",
  importCycle: "Zyklusdaten importieren",
  imported: "Ich habe das übernommen.",
  energyRecent: "Deine Energie",
  emptyEnergy: "Trag kurz ein, wie du dich fühlst.",
  name: "Wie soll ich dich nennen?",
  diet: "Ernährung",
  dietHint: "Damit ich passende Lebensmittel vorschlagen kann.",
  movementProfile: "Bewegung, die du magst",
  referral: "Wie bist du auf Fravia aufmerksam geworden?",
  irregular: "Mein Zyklus ist unregelmäßig",
  endo: "Endometriose",
  endoNone: "Keine",
  endoSuspected: "Verdacht",
  endoDiagnosed: "Diagnostiziert",
  password: "Name und Passwort",
  adjust: "Zuletzt angepasst",
  notFound: "Diese Seite gibt es nicht.",
  home: "Zurück zum Kalender",
  meet: "Lass mich dich kennenlernen.",
  later: "Du kannst alles später anpassen.",
  know: "Los geht's",
  other: "Andere Ausrichtung",
  backCal: "Zurück zum Kalender",
  flexible: "Verschiebbar",
  effort: "Aufwand",
  shared: "Geteilt",
  done: "Erledigt",
  emptyDay: "Noch nichts an diesem Tag.",
  needEnergy: "Noch die Energie.",
  needPain: "Tippe den Schmerz, auch wenn keiner da ist.",
  needFeel: "Tippe, wie der Tag sich anfühlt.",
  welcome: "Willkommen bei Fravia.",
  error: "Das hat leider nicht geklappt. Noch einmal.",
  lengths: "Diese Längen passen so nicht in einen Zyklus.",
  dateMissing: "Das Datum fehlt noch.",
  dateFuture: "Das Datum liegt noch vor dir.",
  unsure: "Ich bin mir nicht sicher",
  standard: "Standard ist 28/5 – ich passe mich an, je mehr du trackst.",
  pillWelcome: "Du bist herzlich willkommen. Bei der Pille gibt es keinen natürlichen Eisprung. Ich begleite dich trotzdem.",
  painFrame: "Nur als Rahmen. Der Tag richtet sich danach, was heute geht.",
  menoFrame: "Da du in den Wechseljahren bist, brauche ich keinen Periodenstart.",
  questionRhythm: "Wann hat deine letzte Periode begonnen?",
  questionPill: "Wann hat die Blutung angefangen, die du wirklich hast?",
  questionPain: "Wann hat deine letzte Periode begonnen?",
  questionMeno: "Wann war die letzte Periode, wenn du sie noch weißt?",
  cycleLen: "Zykluslänge",
  cycleApprox: "Zykluslänge, ungefähr",
  bleedDays: "Wie viele Tage blutet es?",
  bleedDaysPain: "Wie viele Tage blutet es meistens?",
  luteal: "Lutealphase",
  lutealHint: "Tage vom Eisprung bis zur nächsten Periode. Optional, typisch 12–16.",
  pack: "Wie lang ist ein Pack, Pause inklusive?",
  days: "Tage",
  none: "keine",
  light: "leicht",
  medium: "mittel",
  heavy: "stark",
  painNone: "keiner",
  painLight: "spürbar",
  painStrong: "stark",
  painOut: "heute geht wenig",
  moodEven: "tragbar",
  moodThin: "dünn",
  moodRaw: "roh",
  heatNone: "keine",
  heatWarm: "warm",
  heatHot: "heiß",
  sleepSteady: "ruhig",
  sleepBroken: "gebrochen",
  sleepShort: "kurz",
  symCramp: "Krämpfe",
  symHead: "Kopfschmerz",
  symBreast: "Brustspannen",
  symSkin: "Haut",
  symTired: "Müdigkeit",
  symAppetite: "Heißhunger",
  account: "Konto",
  close: "Schließen",
};

const en: typeof de = {
  ...de,
  gateTitle: "Plan your week in step with your cycle.",
  gateBody: "For you. Tasks, appointments, food and movement, matched to your phase.",
  signIn: "Sign in",
  signUp: "Create an account",
  guest: "Continue without an account",
  guestNote: "Guest mode, stored on this device.",
  loading: "I'm fetching your calendar.",
  authFail: "You're signed in, but the calendar doesn't recognise you yet.",
  retry: "Try again",
  revise: "Direction",
  signOut: "Sign out",
  settings: "Settings",
  food: "What helps",
  move: "Movement",
  month: "Month",
  week: "Week",
  year: "Year",
  dayView: "Day",
  todayJump: "Today",
  search: "Search",
  searchEmpty: "Nothing with that word.",
  allDay: "All day",
  place: "Place",
  remind: "Reminder",
  noRemind: "None",
  todayWord: "today",
  checkin: "How are you today?",
  seeToday: "See today",
  save: "Saved",
  saving: "Saving",
  back: "Back",
  note: "A note to myself…",
  bleed: "Bleeding",
  bleedMaybe: "Bleeding, if it's there",
  energy: "Energy",
  low: "very low",
  high: "very good",
  symptoms: "Symptoms",
  ovulation: "Ovulation today",
  pain: "Pain",
  sleep: "Sleep",
  heat: "Heat",
  mood: "Mood",
  day: "This day",
  appointment: "Appointment",
  meal: "Meal",
  sport: "Movement",
  birthday: "Birthday",
  task: "Task",
  add: "Add",
  title: "What should go in?",
  repeat: "Repeat",
  until: "Until",
  onlyThis: "Only this one",
  wholeSeries: "The whole series",
  moveDay: "Another day",
  once: "Once",
  daily: "Daily",
  weekdays: "Mon–Fri",
  weekdaysSat: "Mon–Sat",
  weekly: "Weekly",
  monthly: "Monthly",
  quarterly: "Quarterly",
  halfyearly: "Twice a year",
  yearly: "Yearly",
  voice: "Talk to me",
  voiceHint: "Tap the microphone and speak – or type it here.",
  listening: "I'm listening…",
  voiceLocal: "I understood that on this device. A speech service isn't connected yet.",
  share: "Share calendar",
  shareEmpty: "No shares yet.",
  shareCopy: "Copy link",
  shareHide: "Don't share phases",
  shareAccept: "Accept",
  shareDone: "Calendar added – you'll see the appointments in your calendar.",
  shareMissing: "This invitation is gone.",
  shareNeeds: "That needs an account.",
  shareSign: "Sign in, then you can accept.",
  copied: "Link copied.",
  feed: "Calendar feed",
  feedCopy: "Copy iCal link",
  feedHint: "Subscribe to the link in Apple or Google Calendar.",
  push: "Notifications",
  pushOn: "Turn reminders on",
  pushGap: "Push isn't connected yet. I'll remember that you want a reminder – sending waits until the keys exist.",
  pushOff: "Reminders off",
  pushReady: "I'll remind you if you allow it. Gently, not as a nag.",
  deleteAsk: "Really delete your profile?",
  deleteBody: "This can't be undone. Logs, tasks and appointments go with it.",
  deleteYes: "Yes, delete everything",
  deleteNo: "Cancel",
  feedback: "How do you like Fravia?",
  feedbackHint: "What do you like – and what can I do better?",
  feedbackThanks: "Thank you for the feedback.",
  feedbackSend: "Send",
  language: "Language",
  privacy: "Privacy",
  imprint: "Imprint",
  help: "If something sticks, tell me here. I don't replace a doctor or an emergency service.",
  install: "Install Fravia as an app",
  installIos: "In Safari, share, then Add to Home Screen.",
  update: "A new version is waiting",
  reload: "Reload",
  take: "Take this calendar with you?",
  takeBody: "What you entered without an account is still on this device.",
  takeYes: "Take it",
  leave: "Leave it here",
  guestClear: "Delete local data",
  importIcs: "Import calendar events as .ics",
  importCycle: "Import cycle data",
  imported: "I've taken that in.",
  energyRecent: "Your energy",
  emptyEnergy: "Jot down how you feel.",
  name: "What should I call you?",
  diet: "Food",
  dietHint: "So I can suggest food that fits.",
  movementProfile: "Movement you like",
  referral: "How did you hear about Fravia?",
  irregular: "My cycle is irregular",
  endo: "Endometriosis",
  endoNone: "None",
  endoSuspected: "Suspected",
  endoDiagnosed: "Diagnosed",
  password: "Name and password",
  adjust: "Last adjustment",
  notFound: "This page isn't here.",
  home: "Back to the calendar",
  meet: "Let me get to know you.",
  later: "You can change all of this later.",
  know: "Let's go",
  other: "Another direction",
  backCal: "Back to the calendar",
  flexible: "Movable",
  effort: "Effort",
  shared: "Shared",
  done: "Done",
  emptyDay: "Nothing on this day yet. Add what belongs here.",
  needEnergy: "Energy is still missing.",
  needPain: "Tap the pain, even if there is none.",
  needFeel: "Tap how the day feels.",
  welcome: "Welcome to Fravia.",
  error: "That didn't work. Once more.",
  lengths: "Those lengths don't fit a cycle.",
  dateMissing: "The date is still missing.",
  dateFuture: "That date is still ahead of you.",
  unsure: "I'm not sure",
  standard: "The default is 28/5 – I adjust as you track.",
  pillWelcome: "You are very welcome. On the pill there is no natural ovulation. I'll still walk with you.",
  painFrame: "Only a frame. The day follows what is possible today.",
  menoFrame: "Because you're in menopause, I don't need a period start.",
  questionRhythm: "When did your last period start?",
  questionPill: "When did the bleed you actually have start?",
  questionPain: "When did your last period start?",
  questionMeno: "When was the last period, if you still know?",
  cycleLen: "Cycle length",
  cycleApprox: "Cycle length, roughly",
  bleedDays: "How many days do you bleed?",
  bleedDaysPain: "How many days does the bleed usually last?",
  luteal: "Luteal phase",
  lutealHint: "Days from ovulation to the next period. Optional, typically 12–16.",
  pack: "How long is a pack, pause included?",
  days: "days",
  none: "none",
  light: "light",
  medium: "medium",
  heavy: "heavy",
  painNone: "none",
  painLight: "noticeable",
  painStrong: "strong",
  painOut: "not today",
  moodEven: "okay",
  moodThin: "thin",
  moodRaw: "raw",
  heatNone: "none",
  heatWarm: "warm",
  heatHot: "hot",
  sleepSteady: "steady",
  sleepBroken: "broken",
  sleepShort: "short",
  symCramp: "Cramps",
  symHead: "Headache",
  symBreast: "Breast tenderness",
  symSkin: "Skin",
  symTired: "Tiredness",
  symAppetite: "Cravings",
  account: "Account",
  close: "Close",
};

const es: typeof de = {
  ...en,
  gateTitle: "Planea tu semana en sintonía con tu ciclo.",
  gateBody: "Para ti. Tareas, citas, comida y movimiento, según tu fase.",
  signIn: "Entrar",
  signUp: "Crear cuenta",
  guest: "Seguir sin cuenta",
  guestNote: "Modo invitada, guardado en este dispositivo.",
  loading: "Voy a por tu calendario.",
  revise: "Orientación",
  signOut: "Salir",
  settings: "Ajustes",
  food: "Lo que te sienta bien",
  move: "Movimiento",
  month: "Mes",
  week: "Semana",
  year: "Año",
  dayView: "Día",
  todayJump: "Hoy",
  search: "Buscar",
  searchEmpty: "Nada con esa palabra.",
  allDay: "Todo el día",
  place: "Lugar",
  remind: "Aviso",
  noRemind: "Ninguno",
  todayWord: "hoy",
  checkin: "¿Cómo estás hoy?",
  seeToday: "Ver hoy",
  save: "Guardado",
  saving: "Lo estoy guardando",
  back: "Volver",
  note: "Una nota para mí…",
  bleed: "Sangrado",
  energy: "Energía",
  low: "muy baja",
  high: "muy bien",
  symptoms: "Molestias",
  ovulation: "Ovulación hoy",
  pain: "Dolor",
  sleep: "Sueño",
  heat: "Calor",
  mood: "Ánimo",
  day: "Este día",
  appointment: "Cita",
  meal: "Comida",
  sport: "Deporte",
  birthday: "Cumpleaños",
  task: "Tarea",
  add: "Añadir",
  voice: "Háblame",
  voiceHint: "Toca el micrófono y habla – o escríbelo aquí.",
  listening: "Te escucho…",
  share: "Compartir calendario",
  shareEmpty: "Aún no hay invitaciones.",
  shareAccept: "Aceptar",
  shareDone: "Calendario añadido – verás las citas en el tuyo.",
  push: "Avisos",
  pushOn: "Activar recordatorios",
  pushGap: "Los avisos aún no están conectados. Recuerdo que quieres uno; el envío espera a las claves.",
  deleteAsk: "¿Borrar el perfil de verdad?",
  deleteYes: "Sí, borrar todo",
  deleteNo: "Cancelar",
  feedback: "¿Qué te parece Fravia?",
  feedbackThanks: "Gracias por decírmelo.",
  language: "Idioma",
  privacy: "Privacidad",
  imprint: "Aviso legal",
  help: "Si algo falla, escríbeme aquí. No sustituyo a una médica ni a urgencias.",
  install: "Instalar Fravia como app",
  update: "Hay una versión nueva",
  take: "¿Te llevas este calendario?",
  takeYes: "Llevarlo",
  leave: "Dejarlo aquí",
  name: "¿Cómo te llamo?",
  home: "Volver al calendario",
  meet: "Déjame conocerte.",
  know: "Vamos",
  welcome: "Bienvenida a Fravia.",
  questionRhythm: "¿Cuándo empezó tu última regla?",
  pillWelcome: "Eres muy bienvenida. Con la píldora no hay ovulación natural. Igual te acompaño.",
  menoFrame: "En la menopausia no necesito el inicio de la regla.",
  notFound: "Esta página no está.",
};

const fr: typeof de = {
  ...en,
  gateTitle: "Planifie ta semaine en accord avec ton cycle.",
  gateBody: "Pour toi. Tâches, rendez-vous, repas et mouvement, selon ta phase.",
  signIn: "Se connecter",
  signUp: "Créer un compte",
  guest: "Continuer sans compte",
  guestNote: "Mode invitée, enregistré sur cet appareil.",
  loading: "Je vais chercher ton calendrier.",
  revise: "Orientation",
  signOut: "Se déconnecter",
  settings: "Réglages",
  food: "Ce qui te fait du bien",
  move: "Mouvement",
  month: "Mois",
  week: "Semaine",
  year: "Année",
  dayView: "Jour",
  todayJump: "Aujourd'hui",
  search: "Chercher",
  searchEmpty: "Rien avec ce mot.",
  allDay: "Toute la journée",
  place: "Lieu",
  remind: "Rappel",
  noRemind: "Aucun",
  todayWord: "aujourd'hui",
  checkin: "Comment tu vas aujourd'hui ?",
  seeToday: "Voir aujourd'hui",
  save: "Noté",
  saving: "Je le note",
  back: "Retour",
  note: "Un mot pour moi…",
  bleed: "Saignement",
  energy: "Énergie",
  low: "très basse",
  high: "très bien",
  symptoms: "Gênes",
  ovulation: "Ovulation aujourd'hui",
  pain: "Douleur",
  sleep: "Sommeil",
  heat: "Chaleur",
  mood: "Humeur",
  day: "Ce jour",
  appointment: "Rendez-vous",
  meal: "Repas",
  sport: "Sport",
  birthday: "Anniversaire",
  task: "Tâche",
  add: "Ajouter",
  voice: "Parle-moi",
  voiceHint: "Touche le micro et parle – ou écris ici.",
  listening: "Je t'écoute…",
  share: "Partager le calendrier",
  shareEmpty: "Aucun partage pour l'instant.",
  shareAccept: "Accepter",
  shareDone: "Calendrier ajouté – tu verras les rendez-vous dans le tien.",
  push: "Notifications",
  pushOn: "Activer les rappels",
  pushGap: "Les notifications ne sont pas encore reliées. Je retiens que tu veux un rappel ; l'envoi attend les clés.",
  deleteAsk: "Supprimer le profil pour de bon ?",
  deleteYes: "Oui, tout supprimer",
  deleteNo: "Annuler",
  feedback: "Fravia te plaît ?",
  feedbackThanks: "Merci de me l'avoir dit.",
  language: "Langue",
  privacy: "Confidentialité",
  imprint: "Mentions légales",
  help: "Si quelque chose coince, écris-le ici. Je ne remplace ni une médecin ni les urgences.",
  install: "Installer Fravia comme app",
  update: "Une nouvelle version t'attend",
  take: "Tu emportes ce calendrier ?",
  takeYes: "L'emporter",
  leave: "Le laisser ici",
  name: "Comment je t'appelle ?",
  home: "Retour au calendrier",
  meet: "Laisse-moi faire connaissance.",
  know: "C'est parti",
  welcome: "Bienvenue chez Fravia.",
  questionRhythm: "Quand tes dernières règles ont-elles commencé ?",
  pillWelcome: "Tu es la bienvenue. Sous pilule, pas d'ovulation naturelle. Je t'accompagne quand même.",
  menoFrame: "À la ménopause, je n'ai pas besoin du début des règles.",
  notFound: "Cette page n'existe pas.",
};

export const copy = { de, en, es, fr };

export type CopyKey = keyof typeof de;

export function phrase(lang: Lang, key: CopyKey) {
  return copy[lang][key] ?? copy.de[key];
}
